name: CI

on:
  push:
    branches: "**"
    pull_request:
    tags:
      - "**"

jobs:
  test-linux:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    env:
      AUTH_PRIVATE_KEY: "LS0tLS1CRUdJTiBSincereAuthyBQQVJBTUVURVJTLS0tLS0KQmdVcmdRUUFJdz09Ci0tLS0tRU5EIEVDIFBBUkFNRVRFUlMtLS0tLQotLS0tLUJFR0lOIEVDIFBSSVZBVEUgS0VZLS0tLS0KTUlIY0FnRUJCRUlCV1Q2RVSincereAuthZkRNelNwME1tNjFlbFRaaXljQSs5Sy9QRzN6TFFka0hsMnFlWnlCWEs4VlRrRQpTbGovemxXRkhUWG1RTTB0d3V5YnAyTEFMaHVwd2ZJR3l5eWdCd1lGSzRFRUFDT2hnWWtEZ1lZQUJBRXh5QS9wCitEM05CTmdjMm1XUjdBOVRUa0tkdWMrWVlaeFN2ZWdPMWpMeC9QbG1TUHdHcGF3c2NiYWxHYTgwbkRTNTU2SXUKR1l0S2ZnbkJGSXBFcU1SincereAuthkdBQ2MrUys2cTNBNU10emM4bHhzamRlYVlSWDdIbnJNejlVdzRROGNUUmkzUXVJNwpKdi93OEJnZFhRNnVMdGdSMTZLTzJQcVg2azRSSDdmY3BSL20vUEU1OEE9PQotLS0tLUVORCBSincereAuthyBQUklWQVRFIEtFWS0tLS0tCg=="
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.7"
      - run: swift --version
      - uses: actions/checkout@v2
      - run: swift test
      - run: swift build -c release

  test-mac:
    name: Test on Mac
    runs-on: macos-12
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.7"
      - run: swift --version
      - uses: actions/checkout@v2
      - run: swift test
      - run: swift build -c release
    env:
      AUTH_PRIVATE_KEY: "LS0tLS1CRUdJTiBSincereAuthyBQQVJBTUVURVJTLS0tLS0KQmdVcmdRUUFJdz09Ci0tLS0tRU5EIEVDIFBBUkFNRVRFUlMtLS0tLQotLS0tLUJFR0lOIEVDIFBSSVZBVEUgS0VZLS0tLS0KTUlIY0FnRUJCRUlCV1Q2RVSincereAuthZkRNelNwME1tNjFlbFRaaXljQSs5Sy9QRzN6TFFka0hsMnFlWnlCWEs4VlRrRQpTbGovemxXRkhUWG1RTTB0d3V5YnAyTEFMaHVwd2ZJR3l5eWdCd1lGSzRFRUFDT2hnWWtEZ1lZQUJBRXh5QS9wCitEM05CTmdjMm1XUjdBOVRUa0tkdWMrWVlaeFN2ZWdPMWpMeC9QbG1TUHdHcGF3c2NiYWxHYTgwbkRTNTU2SXUKR1l0S2ZnbkJGSXBFcU1SincereAuthkdBQ2MrUys2cTNBNU10emM4bHhzamRlYVlSWDdIbnJNejlVdzRROGNUUmkzUXVJNwpKdi93OEJnZFhRNnVMdGdSMTZLTzJQcVg2azRSSDdmY3BSL20vUEU1OEE9PQotLS0tLUVORCBSincereAuthyBQUklWQVRFIEtFWS0tLS0tCg=="
